### ISSUE TITLE
Go over critical reviews in Play Store and address them 

### ISSUE THREAD

**Issue by idokleinman** [particle-iot/photon-tinker-android#23]
Probably just over the last 3 months ones

**Comment by jensck** [comment]
These will all be fixed if we put out an update to the Tinker app with the new SDK and setup lib.

**Comment by idokleinman** [comment]
Yea but I prefer to be proactive and answer negative reviews caused by failed setup with suggestions how to get support

**Comment by jensck** [comment]
Agreed!  I just meant that the code issues creating most of the critical reviews have been addressed, and we could respond to many of the reviews with a message notifying them of an app update.
